server:
  port: 8081

logging:
  level:
    root: DEBUG
    org.springframework.web: debug

spring:
  jpa:
    hibernate:
      ddl-auto: update
  application.name: backend-auth
  datasource:
    platform: mysql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/registration?createDatabaseIfNotExist=true
    username: root
    password: password123
    initialization-mode: always
    jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      show-sql: false
      hibernate:
        ddl-auto: create
        use-new-id-generator-mappings: false


  jackson:
    deserialization:
      FAIL_ON_IGNORED_PROPERTIES: false
    serialization:
      INDENT_OUTPUT: false
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_BIGDECIMAL_AS_PLAIN: true
  security:
    oauth2:
      resource:
        jwt:
          key-uri:

      client:
        registration:
          google:
            client-id: mars-client-id
            client-secret: mars-client-secret
            scope: openid,profile,email